'use strict'
var gKeywords = {
    trump: 1,
    politics: 3,
    pets: 3,
    dog: 2,
    puppy: 2,
    baby: 2,
    cat: 1,
    kity: 1,
    kid: 1,
    aliens: 1,
    movie: 6,
    obama: 1,
    wresling: 1,
    haim: 1,
    leonardo: 1,
    neo: 1,
    'lord of the rings': 1,
    'star trek': 1,
    putin: 1,
    'toy story': 1,
    spongebob: 1
}
var gMemes = [
    { id: 1, url: '../img/1.jpg', keywords: ['trump', 'politics'] },
    { id: 2, url: '../img/2.jpg', keywords: ['pets', 'dog', 'puppy'] },
    { id: 3, url: '../img/3.jpg', keywords: ['pets', 'dog', 'puppy', 'baby'] },
    { id: 4, url: '../img/4.jpg', keywords: ['pets', 'cat', 'kity'] },
    { id: 5, url: '../img/5.jpg', keywords: ['kid'] },
    { id: 6, url: '../img/6.jpg', keywords: ['aliens'] },
    { id: 7, url: '../img/7.jpg', keywords: ['baby'] },
    { id: 8, url: '../img/8.jpg', keywords: ['movie'] },
    { id: 9, url: '../img/9.jpg', keywords: ['baby'] },
    { id: 10, url: '../img/10.jpg', keywords: ['obama', 'politics'] },
    { id: 11, url: '../img/11.jpg', keywords: ['wresling'] },
    { id: 12, url: '../img/12.jpg', keywords: ['haim'] },
    { id: 13, url: '../img/13.jpg', keywords: ['movie', 'leonardo'] },
    { id: 14, url: '../img/14.jpg', keywords: ['movie', 'neo'] },
    { id: 15, url: '../img/15.jpg', keywords: ['movie', 'lord of the rings'] },
    { id: 16, url: '../img/16.jpg', keywords: ['movie', 'star trek'] },
    { id: 17, url: '../img/17.jpg', keywords: ['putin', 'politics'] },
    { id: 18, url: '../img/18.jpg', keywords: ['movie', 'toy story'] },
    { id: 19, url: '../img/19.jpg', keywords: ['spongebob'] }
]